### ISSUE TITLE
Where to get SLACK_API_TOKEN 

### ISSUE THREAD

**Issue by ddavaham** [OrthoLoess/jamyl-bot#29]
I hate to post an "Issue" about this but I am unable to find this token. I think I found the admin token but I am obviously not going to reveal it.

The only thing i can find is a client id and client secret. Now there are test api tokens, but nothing about production.

Any assistance with this?

**Comment by OrthoLoess** [comment]
The slack API oauth stuff has been changed a lot since the instructions were made.

The token that jamyl is expecting is still available from here: https://api.slack.com/docs/oauth-test-tokens

I know it's talking about test tokens, but it still works for mine. Obviously it could do with changing at some point.
